"""init tables

Revision ID: 049f6f7d8e44
Revises: 
Create Date: 2026-05-04 12:47:44.916614
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "049f6f7d8e44"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('envelope_id', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###